export type NotificationType =
  | 'JOURNEY_INVITE'
  | 'JOURNEY_STARTED'
  | 'JOURNEY_ENDED'
  | 'LAG_ALERT'
  | 'PARTICIPANT_JOINED'
  | 'PARTICIPANT_LEFT'
  | 'ARRIVAL_DETECTED'
  | 'CONVOY_JOINED'
  | 'JOURNEY_REMINDER'
  | 'JOURNEY_STARTING_NOW'
  | 'JOURNEY_MISSED_START';

export type LagSeverity = 'WARNING' | 'CRITICAL';

export type LagCooldownClaimResult = 'ACQUIRED' | 'SUPPRESSED' | 'UNAVAILABLE';
